<?php
/**
 * AI Deployment Assistant Configuration
 * Auto-generated by Demetrly
 */

return [
    // Site Information
    'SITE_NAME' => '{{SUBDOMAIN_NAME}}',
    'FULL_DOMAIN' => '{{FULL_DOMAIN}}',
    'WEBSITE_URL' => 'https://{{FULL_DOMAIN}}',

    // Database Configuration (if created)
    'DB_NAME' => '{{DB_NAME}}',
    'DB_HOST' => 'localhost',
    'DB_USER' => '{{DB_USER}}',
    'DB_PASS' => '{{DB_PASS}}',

    // Anthropic API Key (for AI assistant)
    'ANTHROPIC_API_KEY' => '{{ANTHROPIC_API_KEY}}',

    // Description
    'DESCRIPTION' => '{{DESCRIPTION}}',
];
